
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nn-deployment
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: namenode-app
  template:
    metadata:
      labels:
        app: namenode-app    
    spec:
      containers:
      - name: namenode-app
        image: raanglada/hadoop-namenode:2.9.2
        imagePullPolicy: IfNotPresent
        ports:
         - containerPort: 9000
         - containerPort: 50070                 
         - containerPort: 19888
         - containerPort: 8088
         - containerPort: 22
         - containerPort: 8031
#        resources:
#          requests:
#            memory: "1024Mi"
#            cpu: "25m"
#          limits:
#            memory: "2048Mi"
#            cpu: "50m"
