apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  ports:
    - name: hdfs
      port: 9000
      targetPort: 9000
    - name: nn-ui
      port: 50070
      targetPort: 50070
    - name: yarn-ui
      port: 8088
      targetPort: 8088
    - name: yarn-server
      port: 8031
      targetPort: 8031
       

