apiVersion: apps/v1
kind: Deployment
metadata:
  name: datanode-deployment
spec:  
  replicas: 1
  selector:
    matchLabels:
      app: datanode
  template:
    metadata:
      labels:
        app: datanode 
    spec:      
      containers:
      - name: namenode
        image: raanglada/hadoop-datanode:2.9.2
        imagePullPolicy: IfNotPresent
