
From raanglada/hadoop-base

MAINTAINER Anglada <anglada.alex@gmail.com>

LABEL Description="Namenode and resource manager image for hadoop cluster"

ADD nn/hdfs-site.xml $HADOOP_HOME/etc/hadoop/
ADD nn/start-namenode.sh /

CMD bash /start-namenode.sh

