version: '3'
services:
  namenode:
    build:
      context: .      
      dockerfile: ./nn-rm/Dockerfile 
    image: raanglada/hadoop-namenode    
    restart: always
    ports:
      - 50070:50070
      - 8088:8088 
      - 19888:1988  

  datanode:
    build:
      context: .
      dockerfile: ./datanode/Dockerfile
    image: raanglada/hadoop-datanode    
    restart: always       
      
    