version: '3'
services:
  namenode:
    container_name: namenode
    build:
      context: .      
      dockerfile: ./nn-rm/Dockerfile 
    image: raanglada/hadoop-namenode:2.9.2    
    restart: always
    extra_hosts:    
      - "namenode:192.168.0.10"
    networks:
      hadoop-network:
        ipv4_address: 192.168.0.10
    ports:
      - "8088:8088"
      - "50070:50070"      
      - "19888:19888"
      - "9000:9000"

  datanode:    
    build:
      context: .
      dockerfile: namenode./datanode/Dockerfile
    image: raanglada/hadoop-datanode:2.9.2    
    restart: always
    networks:
      hadoop-network:
    extra_hosts:    
      - "namenode:192.168.0.10"
      
networks:
  hadoop-network:
    driver: bridge
    ipam:      
      config:
        - subnet: "192.168.0.0/16"          

